authors:
  team:
    name: Команда
    description: Сотрудники МЦ Ваш Доктор
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  aavakhrameev:
    name: Anton Vakhrameev
    description: Creator
    avatar: https://github.com/squidfunk.png